### ISSUE TITLE
[Feature Request] Add status to filter for listing check deposits

### ISSUE THREAD

**Issue by rolycg** [unit-finance/unit-python-sdk#201]
Hi team, 

Can we add `status` as a filter field for check deposits?
https://docs.unit.co/check-deposits/#list-check-deposits

**Comment by Yaellever** [comment]
@rolycg Thanks for contacting us
The Unit SDK does not support filtering the List Check Deposits by status at them moment so cannot be added to the SDK. To request this feature to be added to the API, please contact your success manager or solution engineers via your Slack channel and it will be prioritised for development. I recommend noting in your request that you would  like this feature to be added to the Python SDK when it's deployed so that we will be notified of this requirement directly when it's ready.
